steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'PUBLIC_API_URL=${_PUBLIC_API_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/modtale-frontend:${_TAG}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/modtale-frontend:${_TAG}']

substitutions:
  _PUBLIC_API_URL: http://localhost:8080/api/v1
  _TAG: latest