steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/$PROJECT_ID/modtale-backend:${_TAG} || true
        docker build \
          --cache-from gcr.io/$PROJECT_ID/modtale-backend:${_TAG} \
          -t gcr.io/$PROJECT_ID/modtale-backend:${_TAG} \
          .

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/modtale-backend:${_TAG}']

substitutions:
  _TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY
