from pathlib import Path
import html,json,subprocess,hashlib
B=Path(__file__).resolve().parents[1];e=html.escape
posts=json.loads((B/'twitter/posts.json').read_text());discord=(B/'discord/announcement.txt').read_text()
def video(path,poster):return f'<video controls playsinline preload="none" poster="{poster}"><source src="{path}" type="video/mp4"></video>'
def stats(path):
 p=B/path
 if not p.exists():return 'Rendering'
 d=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration,size','-of','json',str(p)]))['format'];return f"{float(d['duration']):g}s · {int(d['size'])/1000000:.1f} MB"
cards=[]
for p in posts:
 path='twitter/'+p['video'];poster='twitter/'+p['poster']
 cards.append(f'''<article class="tweet"><div class="cardtop"><span class="eyebrow">{e(p['slot'])}</span><span class="count">{p['characters']}/280</span></div>{video(path,poster)}<div class="copy"><h3>{e(p['title'])}</h3><pre id="{p['id']}">{e(p['text'])}</pre><div class="actions"><button data-copy="{p['id']}">Copy tweet</button><a href="{path}" download>Download video</a><a href="{poster}" download>Cover</a></div><small>{stats(path)} · {p['remaining']} characters spare</small></div></article>''')
css='''@font-face{font-family:Inter;src:url(source/Inter-Regular.ttf);font-weight:400}@font-face{font-family:Inter;src:url(source/Inter-ExtraBold.ttf);font-weight:800}*{box-sizing:border-box}html{scroll-behavior:smooth}body{background:#0a111e;color:#d6e1f2;font:16px/1.6 Inter,system-ui;margin:0}a{color:#94c1ff;text-decoration:none}a:hover{color:white}h1,h2,h3{color:#f7faff;line-height:1.18;font-weight:800}h1{font-size:clamp(38px,5vw,64px);letter-spacing:-2px;max-width:800px;margin:28px 0 20px}h2{font-size:34px;margin:0 0 16px}h3{font-size:22px;margin:18px 0}p{max-width:800px;color:#a9bad1}main{max-width:1400px;margin:auto;padding:0 36px 80px}header{padding:42px 0 52px;border-bottom:1px solid #24334b}header img{width:240px}nav{display:flex;gap:10px;flex-wrap:wrap;margin:30px 0}nav a,.actions a,button{border:1px solid #304565;border-radius:10px;padding:9px 15px;background:#16233b;color:#c4dcff;font:800 13px Inter;cursor:pointer}button:hover,nav a:hover{background:#245bd0;color:white}.pill,.count{font-size:12px;color:#aad0ff;background:#142744;padding:5px 10px;border-radius:6px;white-space:nowrap}.pill{margin-left:24px}.facts{display:flex;gap:32px;margin-top:25px}.facts strong{color:#fff;font-size:28px}.facts span{font-size:13px;color:#869cb8}section{padding-top:60px;scroll-margin-top:20px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:25px}.article,.tweet,.panel{background:#111c2e;border:1px solid #273950;border-radius:20px;overflow:hidden}.article img{width:100%;aspect-ratio:40/21;object-fit:cover}.copy,.panel{padding:24px}.article .copy{padding:24px}.cardtop{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:16px 22px}.eyebrow{font-size:12px;font-weight:800;color:#8ca6c9;letter-spacing:.6px}.tweet video{width:100%;display:block;background:#080e18;aspect-ratio:5/4}video{width:100%;border-radius:10px}pre{font:16px/1.7 Inter;white-space:pre-wrap;overflow-wrap:anywhere;color:#e3ecf9;margin:18px 0 25px}.actions{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.actions a{font-weight:400}small{display:block;color:#859ab7;margin-top:15px}details{border:1px solid #2d405d;border-radius:15px;padding:22px;margin:24px 0}summary{font-weight:800;cursor:pointer;color:#dbeafe}table{border-collapse:collapse;width:100%;font-size:14px;margin-top:20px}td,th{text-align:left;padding:15px;border-bottom:1px solid #25364e;vertical-align:top}th{color:#9ebde5}.note{border-left:3px solid #508be8;padding:12px 18px;background:#112138;border-radius:0 10px 10px 0;margin:25px 0;color:#b4c5dd}.discord{align-items:start}.footer{margin-top:60px;border-top:1px solid #28394f;padding-top:20px;font-size:13px;color:#7f95b2}@media(max-width:850px){.grid{grid-template-columns:1fr}main{padding:0 18px 50px}.pill{display:inline-block;margin:15px 0}.facts{gap:22px}header{padding-top:28px}h1{letter-spacing:-1px}.copy,.panel{padding:20px}}'''
intro=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Modtale · Update media brief</title><style>{css}</style><main><header><img src="source/logo.svg" alt="Modtale"><span class="pill">LOCAL DRAFT · FOR REVIEW</span><h1>One update.<br>Three ways to tell the story.</h1><p>Modpacks v2 and the Modtale Launcher. The full articles, a concise community announcement, and a series of feature videos for the feed.</p><div class="facts"><div><strong>2</strong><br><span>article drafts</span></div><div><strong>14</strong><br><span>finished video exports</span></div><div><strong>13</strong><br><span>character-checked tweets</span></div></div><nav><a href="#articles">01 · Articles</a><a href="#discord">02 · Discord + trailer</a><a href="#twitter">03 · Twitter series</a><a href="#research">Since June 10</a><a href="BRIEF.md">Full brief</a></nav></header>'''
articles='''<section id="articles"><span class="eyebrow">01 / THE FULL STORY</span><h2>The articles</h2><p>Existing long-form drafts, packaged with their current media. Open the complete offline versions below; the text copies are available alongside them.</p><div class="grid">'''
for slug,title,desc in [('modtale-launcher','Meet the Modtale Launcher','Discovery, your worlds, updates, sync, and Wardrobe.'),('modpacks-v2','Modpacks v2: from your world to theirs','Versions, config defaults, external projects, and shared setups.')]:
 name='launcher-thumbnail.png' if slug=='modtale-launcher' else 'modpacks-thumbnail.png'
 articles+=f'<article class="article"><a href="articles/{slug}.html"><img src="articles/assets/{name}" alt="{e(title)}"></a><div class="copy"><h3>{e(title)}</h3><p>{desc}</p><div class="actions"><a href="articles/{slug}.html">Read article</a><a href="articles/{slug}.md">Text copy</a></div></div></article>'
articles+='</div></section>'
disc=f'''<section id="discord"><span class="eyebrow">02 / THE COMMUNITY ANNOUNCEMENT</span><h2>A quick tour, together.</h2><p>A 36-second overview of both products. Clear on-screen hooks, actual product footage, and no sound required.</p><div class="grid discord"><div>{video('discord/combined-overview.mp4','discord/combined-overview.jpg')}<small>{stats('discord/combined-overview.mp4')}</small><div class="actions"><a href="discord/combined-overview.mp4" download>Download trailer</a><a href="discord/combined-overview.jpg" download>Cover</a></div></div><div class="panel"><span class="eyebrow">DISCORD ANNOUNCEMENT</span><pre id="discord-copy">{e(discord)}</pre><div class="actions"><button data-copy="discord-copy">Copy announcement</button><a href="discord/announcement.txt">Plain text</a></div></div></div></section>'''
twitter='''<section id="twitter"><span class="eyebrow">03 / A SERIES FOR THE FEED</span><h2>Start broad. Then show the details.</h2><p>The first post has its own 15-second overview. Each following post pairs one benefit with one video. Day labels are a suggested release sequence, not a schedule.</p><div class="note">All tweets fit the standard 280-character limit, counting each URL as 23 characters. Every video is within standard X upload limits. Nothing has been posted or scheduled.</div><div class="grid">'''+''.join(cards)+'</div></section>'
research='''<section id="research"><span class="eyebrow">THE CATCH-UP AUDIT</span><h2>What else changed since June 10?</h2><p>Checked repository history against current code and working UI. Implementation dates are not assumed to be public launch dates.</p><table><thead><tr><th>Feature</th><th>Decision</th><th>Evidence</th></tr></thead><tbody><tr><td>Open-source discovery</td><td>Included: tweet 12 + a new working filter demo.</td><td>June 20 · fac0b2c1</td></tr><tr><td>Project galleries</td><td>Included: tweet 13 + LevelingCore gallery navigation.</td><td>June 15 · 76592452</td></tr><tr><td>CurseForge project-to-draft import</td><td>Excluded: added September 8, removed September 10. Pack-file inclusion is a separate, supported feature in tweet 8.</td><td>f8451bd7 → 68328167</td></tr><tr><td>Pinned comments / batch gallery uploads</td><td>Useful creator follow-ups; deferred to keep this campaign focused.</td><td>September 3 / 7</td></tr></tbody></table><details><summary>Release handoff and claim boundaries</summary><p>Approve copy and media before entering them into external services. Confirm both public news URLs and the intended launcher download channel before publishing. Existing article dates should match the approved release date.</p><p>Sync covers Modtale installs, launcher preferences, and supported configs; world saves stay local. CurseForge-containing packs install through the launcher. Wardrobe previews do not grant cosmetic ownership. Converting a shared list creates a draft.</p><p>Full evidence and exclusions: <a href="BRIEF.md">brief</a> · <a href="source/history.txt">commit audit</a> · <a href="review/validation.json">media validation</a>.</p><p>Platform references: <a href="https://docs.x.com/fundamentals/counting-characters">X character rules</a> · <a href="https://help.x.com/en/using-x/x-videos">video limits</a>.</p></details></section>'''
js='''<script>document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{const t=document.getElementById(b.dataset.copy).textContent;try{await navigator.clipboard.writeText(t);b.textContent='Copied';setTimeout(()=>b.textContent=b.dataset.copy==='discord-copy'?'Copy announcement':'Copy tweet',1800)}catch{const s=getSelection(),r=document.createRange();r.selectNodeContents(document.getElementById(b.dataset.copy));s.removeAllRanges();s.addRange(r);b.textContent='Text selected — copy it'}}));document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause()})));</script>'''
(B/'index.html').write_text(intro+articles+disc+twitter+research+'<div class="footer">Prepared September 10, 2026 · Private review package · Inter typography · Captured product UI</div></main>'+js+'</html>')
print('Review page built.')
